language: generic

sudo: required

services:
  - docker

notifications:
  email: false

env:
  - OTP_VERSION=22.0.4 ELIXIR_VERSION=1.9.0

cache:
  directories:
    - docker-otp-22.0.4-elixir-1.9.0

before_install:
  -
    if [ -e "docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION}/image.tar" ]; then
      docker load -i "docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION}/image.tar";
    else
      docker build -t docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION} -f priv/Dockerfile.otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION} priv;
      mkdir -p "docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION}"; docker save -o "docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION}/image.tar" docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION};
    fi

script:
  - docker run --rm -v `pwd`:/build/http_signature docker-otp-${OTP_VERSION}-elixir-${ELIXIR_VERSION} /bin/bash -c 'cd http_signature && mix deps.get && mix test && rm -rf _build deps ebin && make tests'
