FROM bitwalker/alpine-elixir:1.9.0

RUN apk add --no-cache autoconf bash build-base make openssl

ENV MIX_ENV=test TERM=xterm

RUN mix local.hex --force && mix local.rebar --force

RUN mkdir /build
WORKDIR /build
